### PR TITLE
Add some missing imports

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by itamarhaber** [comment]
Hello @cclauss 

TY for the PR. Out of curiosity, is this some auto-linter complaining or an actual cause for errors?

**Comment by cclauss** [comment]
My bet is that this is dead code that is never getting executed.  If the current code was executed without these changes then exceptions would be raised.

**Comment by itamarhaber** [comment]
Not dead code, for sure, but both run in embedded interpreters that apparently provide these imports during runtime.

**Comment by cclauss** [comment]
Ahh... So some _other file__ imports them _before_ these lines get executed.  That means that they are _implicit_ imports that could stop work if other files are changed.  This one of the reasons that the Zen of Python (import this) says that _explicit is better than implicit_.

**Pull request merged**
